Attribute VB_Name = "Module24"
Sub IdentifyPatentOffices()
    Dim rng As Range
    Dim cell As Range
    Dim patentNumbers As Variant
    Dim output As String
    Dim uniqueOffices As Collection
    Dim patentOffice As Variant
    Dim i As Long
    
    ' Set the range of cells with patent numbers
    Set rng = Selection
    
    ' Loop through each cell in the selected range
    For Each cell In rng
        patentNumbers = Split(cell.Value, "; ")
        output = ""
        Set uniqueOffices = New Collection
        
        ' Loop through each patent number in the cell
        For i = LBound(patentNumbers) To UBound(patentNumbers)
            Select Case Left(patentNumbers(i), 2)
                Case "EP"
                    patentOffice = "European Patent Office"
                Case "US"
                    patentOffice = "United States"
                Case "CN"
                    patentOffice = "China"
                Case "KR"
                    patentOffice = "South Korea"
                Case "JP"
                    patentOffice = "Japan"
                Case "WO"
                    patentOffice = "World Intellectual Property Organization"
                Case "DE"
                    patentOffice = "Germany"
                Case "FR"
                    patentOffice = "France"
                Case "GB"
                    patentOffice = "United Kingdom"
                Case "CA"
                    patentOffice = "Canada"
                Case "AU"
                    patentOffice = "Australia"
                Case "ES"
                    patentOffice = "Spain"
                Case "CH"
                    patentOffice = "Switzerland"
                Case "IT"
                    patentOffice = "Italy"
                Case "NL"
                    patentOffice = "Netherlands"
                Case "SE"
                    patentOffice = "Sweden"
                Case "AT"
                    patentOffice = "Austria"
                Case "BR"
                    patentOffice = "Brazil"
                Case "RU"
                    patentOffice = "Russia"
                Case "IN"
                    patentOffice = "India"
                Case "MX"
                    patentOffice = "Mexico"
                Case "ZA"
                    patentOffice = "South Africa"
                Case "SG"
                    patentOffice = "Singapore"
                Case "IL"
                    patentOffice = "Israel"
                Case "MY"
                    patentOffice = "Malaysia"
                Case "NZ"
                    patentOffice = "New Zealand"
                Case "FI"
                    patentOffice = "Finland"
                Case "NO"
                    patentOffice = "Norway"
                Case "DK"
                    patentOffice = "Denmark"
                Case "BE"
                    patentOffice = "Belgium"
                Case "PL"
                    patentOffice = "Poland"
                Case "PT"
                    patentOffice = "Portugal"
                Case "GR"
                    patentOffice = "Greece"
                Case "HU"
                    patentOffice = "Hungary"
                Case "CZ"
                    patentOffice = "Czech Republic"
                Case "IE"
                    patentOffice = "Ireland"
                Case "LU"
                    patentOffice = "Luxembourg"
                Case "SK"
                    patentOffice = "Slovakia"
                Case "BG"
                    patentOffice = "Bulgaria"
                Case "RO"
                    patentOffice = "Romania"
                Case "SI"
                    patentOffice = "Slovenia"
                Case "LT"
                    patentOffice = "Lithuania"
                Case "EE"
                    patentOffice = "Estonia"
                Case "LV"
                    patentOffice = "Latvia"
                Case "HR"
                    patentOffice = "Croatia"
                Case "CY"
                    patentOffice = "Cyprus"
                Case "IS"
                    patentOffice = "Iceland"
                Case "TR"
                    patentOffice = "Turkey"
                Case "UA"
                    patentOffice = "Ukraine"
                Case "BY"
                    patentOffice = "Belarus"
                Case "AM"
                    patentOffice = "Armenia"
                Case "GE"
                    patentOffice = "Georgia"
                Case "UZ"
                    patentOffice = "Uzbekistan"
                Case "KZ"
                    patentOffice = "Kazakhstan"
                Case "MD"
                    patentOffice = "Moldova"
                Case "KG"
                    patentOffice = "Kyrgyzstan"
                Case "AZ"
                    patentOffice = "Azerbaijan"
                Case "MN"
                    patentOffice = "Mongolia"
                Case "VN"
                    patentOffice = "Vietnam"
                Case "PH"
                    patentOffice = "Philippines"
                Case "TH"
                    patentOffice = "Thailand"
                Case "ID"
                    patentOffice = "Indonesia"
                Case "PK"
                    patentOffice = "Pakistan"
                Case "EG"
                    patentOffice = "Egypt"
                Case "AR"
                    patentOffice = "Argentina"
                Case "CL"
                    patentOffice = "Chile"
                Case "CO"
                    patentOffice = "Colombia"
                Case "PE"
                    patentOffice = "Peru"
                Case "VE"
                    patentOffice = "Venezuela"
                Case "CU"
                    patentOffice = "Cuba"
                Case "CR"
                    patentOffice = "Costa Rica"
                Case "DO"
                    patentOffice = "Dominican Republic"
                Case "GT"
                    patentOffice = "Guatemala"
                Case "HN"
                    patentOffice = "Honduras"
                Case "JM"
                    patentOffice = "Jamaica"
                Case "TT"
                    patentOffice = "Trinidad and Tobago"
                Case "UY"
                    patentOffice = "Uruguay"
                Case "EC"
                    patentOffice = "Ecuador"
                Case "SV"
                    patentOffice = "El Salvador"
                Case "PA"
                    patentOffice = "Panama"
                Case "BO"
                    patentOffice = "Bolivia"
                Case "PY"
                    patentOffice = "Paraguay"
                Case "KE"
                    patentOffice = "Kenya"
                Case "NG"
                    patentOffice = "Nigeria"
                Case "GH"
                    patentOffice = "Ghana"
                Case "TZ"
                    patentOffice = "Tanzania"
                Case "ZM"
                    patentOffice = "Zambia"
                Case "MW"
                    patentOffice = "Malawi"
                Case "SL"
                    patentOffice = "Sierra Leone"
                Case "GM"
                    patentOffice = "Gambia"
                Case "ZW"
                    patentOffice = "Zimbabwe"
                Case "BW"
                    patentOffice = "Botswana"
                Case "LS"
                    patentOffice = "Lesotho"
                Case "NA"
                    patentOffice = "Namibia"
                Case "SZ"
                    patentOffice = "Swaziland"
                Case "MZ"
                    patentOffice = "Mozambique"
                Case "CM"
                    patentOffice = "Cameroon"
                Case "LR"
                    patentOffice = "Liberia"
                Case "AO"
                    patentOffice = "Angola"
                Case "ET"
                    patentOffice = "Ethiopia"
                Case "RW"
                    patentOffice = "Rwanda"
                Case "UG"
                    patentOffice = "Uganda"
                Case "SD"
                    patentOffice = "Sudan"
                Case "DZ"
                    patentOffice = "Algeria"
                Case "LY"
                    patentOffice = "Libya"
                Case "MA"
                    patentOffice = "Morocco"
                Case "TN"
                    patentOffice = "Tunisia"
                Case "OM"
                    patentOffice = "Oman"
                Case "QA"
                    patentOffice = "Qatar"
                Case "KW"
                    patentOffice = "Kuwait"
                Case "AE"
                    patentOffice = "United Arab Emirates"
                Case "SA"
                    patentOffice = "Saudi Arabia"
                Case "BH"
                    patentOffice = "Bahrain"
                Case "LB"
                    patentOffice = "Lebanon"
                Case "SY"
                    patentOffice = "Syria"
                Case "IQ"
                    patentOffice = "Iraq"
                Case "IR"
                    patentOffice = "Iran"
                Case "JO"
                    patentOffice = "Jordan"
                Case "YE"
                    patentOffice = "Yemen"
                Case Else
                    patentOffice = ""
            End Select
            
            ' Add the office to the collection if it's not already there
            On Error Resume Next
            If Len(patentOffice) > 0 Then
                uniqueOffices.Add patentOffice, CStr(patentOffice)
            End If
            On Error GoTo 0
        Next i
        
        ' Concatenate the unique offices into the output string
        For i = 1 To uniqueOffices.count
            output = output & uniqueOffices(i) & ", "
        Next i
        
        ' Remove the trailing comma and space
        If Len(output) > 0 Then
            output = Left(output, Len(output) - 2)
        End If
        
        ' Output the result in the adjacent cell
        cell.Offset(0, 1).Value = output
    Next cell
End Sub
